CodeForAfrica/PesaYetu

src/components/Hero/index.js
src/components/HowItWorks/useStyles.js

Remove horizontal scrolling on page

[HotFix] Remove horizontal Scrolling

---

src/functions/menus/formatHeirarchialMenu.js
src/functions/menus/getFooterMenu.js

Remove prefixt of menu path in cms

[HotFix] Remove Menu Multisite Prefix

---

src/components/NewsInsight/index.js
src/components/NewsInsight/index.stories.js

[Feature] News Insight Section

---

src/components/AboutHero/index.js
src/components/AboutHero/index.stories.js
src/components/AboutHero/useStyles.js
src/components/Header/index.js
src/components/Header/index.stories.js
src/components/Hero/index.js
src/components/Hero/index.stories.js
src/components/InsightsData/index.js
src/components/InsightsData/useStyles.js
src/components/OtherHero/index.js
src/components/OtherHero/index.stories.js
src/config.js
src/theme/index.js

Introduce reusable `Header` component (`H0` in the XDs). This component also helps us standardize CMS props for a heading: `title` (required), `overline` and `subtitle` (both optional).

[Feature] Header

---

src/components/Menu/index.js
src/components/Page/Base.js
src/components/SocialMediaIcons/index.js
src/config.js
src/functions/menus/getNavigationMenu.js
src/theme/index.js

Add navigation cms

---

src/components/AboutTeam/index.js
src/components/AboutTeam/useStyles.js

Fix for About Team
Please delete options that are not relevant.

[Fix] - About Team Fix

---

src/pages/index.js

Arrange homepage Block and CMS to conform to design
Fixes # ([178719381](https://www.pivotaltracker.com/story/show/178719381))
Please delete options that are not relevant.

[Chore] Homepage

---

src/components/DataVisuals/index.js
src/components/ExploreOtherTools/index.js
src/functions/formatBlocksForSections.js
src/pages/index.js

- Rename DataVisual blocks
- If no items, return null

[HotFix] Check if items has length

---

src/pages/about.js
src/pages/api/exit-preview.js
src/pages/api/preview.js

[Chore] Preview API

---

.env.sample

A few changes have been added/removed from env file but the sample file hasn't been updated to reflect these changes e.g. `WAZIMAP_API_URL` was changed to `HURUMAP_API_URL`, etc.
N/A

[HotFix] Update .env.sample to reflect recent changes

---

src/components/HURUmap/Map/Layers.js

[HotFix] Fix Warning

---

package.json
src/config.js
src/utils/fetchProfile.js
src/utils/formatNumericalValue.js
yarn.lock

This PR introduces number formatting to the fetchProfile function so that we can format all numeric values in a single place. (Profile) Highlights are used as proof of code.

[Feature] Number Formatting

---

src/assets/icons/expand_more.svg
src/components/DatasetsAndDocuments/index.js
src/components/DatasetsAndDocuments/useStyles.js
src/components/Sources/CarouselItem.js
src/components/Sources/Dataset.js
src/components/Sources/Document.js
src/components/Sources/index.js
src/components/Sources/useStyles.js
src/components/SourcesFilter/index.js
src/components/SourcesFilter/input.js
src/pages/data/[[...slug]].js
src/theme/index.js

Simplify and fix components on data page

[Fix] Data page

---

src/components/HURUmap/Tutorial/index.js
src/components/Summary/index.js
src/components/TooltipBanner/index.js
src/pages/explore/[[...slug]].js
src/pages/how-it-works.js

Show tooltip banner on How it works page. Clicking the button should link to Tutorial on the Explore page.

[Feature] How it works tooltip

---

src/components/OtherHero/index.js

Fixes # 179685152
##Current
##Fix

[Fix ] otherHero component on tablet && desktop

---

src/components/HowItWorks/Player.js

Switch to recommended VideoJS/React setup to hopeful fix the console errors: `VIDEOJS: ERROR: SyntaxError: Unexpected token o in JSON at position 1`
Setup: <https://docs.videojs.com/tutorial-react.html>

[Fix] VideoJS

---

src/assets/icons/Group922.svg
src/assets/icons/Group923.svg
src/components/HURUmap/IndicatorTitle/Download.js
src/components/HURUmap/IndicatorTitle/Share.js
src/components/HURUmap/IndicatorTitle/useStyles.js
src/config/index.js

- Update Icons for layout option on  Indicator Title 

Update Layout Icons

---

src/components/HURUmap/Chart/Filters.js
src/components/HURUmap/Chart/index.js
src/components/HURUmap/Chart/utils.js

[HotFix] Fix filters

---

next-seo.config.js
src/functions/menus/formatHeirarchialMenu.js
src/functions/postTypes/getFrontendPage.js
src/functions/postTypes/getPostTypeTaxonomyArchive.js
src/functions/postTypes/processPostTypeQuery.js
src/functions/replaceMultisitePrefix.js
src/functions/seo/formatArchiveSeoData.js

- Fix canonical, replace pathname

[Bug] Fix canonical

---

src/components/SupportingPartners/index.js

~~greyscale~~`mix-blend-mode: luminosity` + clean up

[Feat] Supporting Partner Logos

---

src/components/FeaturedStoryCard/index.js
src/components/FeaturedStoryCard/useStyles.js
src/components/Pagination/index.js
src/components/Pagination/index.stories.js
src/components/Stories/List.js
src/components/Stories/index.js
src/components/Stories/useStyles.js
src/components/StoriesPage/index.js
src/components/Tabs/index.js
src/functions/postTypes/getPostTypeTaxonomyArchive.js
src/lib/wordpress/_query-partials/archivePageInfo.js
src/lib/wordpress/categories/queryPostsByCategory.js
src/lib/wordpress/posts/queryPostsArchive.js
src/pages/api/wp/archive.js
src/pages/stories/[[...slug]].js
src/utils/formatStoryPosts.js

- Remove carousel slider, and add offset pagination with button clicks

Stories Pagination

---

src/components/Card/useStyles.js
src/components/DropdownSearch/index.js
src/components/ExploreOtherTools/index.js
src/components/ExploreOtherTools/useStyles.js
src/components/Hero/Map/index.js
src/components/Hero/index.js
src/components/Stories/List.js
src/components/Stories/useStyles.js
src/components/StoriesInsights/CarouselItem.js
src/components/StoriesInsights/useStyles.js
src/lib/wordpress/posts/queryPostById.js
src/pages/stories/[[...slug]].js

- Autosuggest counties for homepage & menu search dropdown
- Custom Author name on post
- Add line limit for card description & content
- Disable any type of zooming for hero Map

[Chores] Custom Author Name & Other chores

---

src/components/DropdownSearch/index.js
src/config/index.js

- Change licence name spelling on footer
- Change name to lowercase on filtering 

[Hotfix] Change Licence Name on Footer

---

src/components/Page/Base.js
src/config/index.js
src/functions/menus/getNavigationMenu.js

[Fix] Update nav social media links

---

src/components/HURUmap/IndicatorTitle/Share.js

[Fix] Update twitter share title

---

.env.sample
public/site.webmanifest
src/components/HURUmap/IndicatorTitle/Download.js
src/components/HURUmap/IndicatorTitle/Share.js
src/config/index.js
src/lib/createChartImage.js
src/pages/_document.js
src/pages/embed/[geoCode]/[chartId].js

[Fix] Social media image

---

src/components/Card/Media.js
src/components/Metrics/index.js

[Fix] Optimize Metric image

---

src/components/HURUmap/IndicatorTitle/index.js
src/components/HURUmap/Panel/DesktopPanel/PanelButtons.js
src/components/HURUmap/Panel/Profile.js
src/components/HURUmap/Panel/ProfileItems.js
src/components/HURUmap/TreeView/index.js
src/components/Loading/index.js
src/components/Loading/index.stories.js
src/components/Stories/index.js

- Move metrics top of the subcategory
- Fix indicator/ Chart description overflow

[Chore] Metrics positon and Indicator Description

---

src/components/HURUmap/IndicatorTitle/Action.js
src/components/HURUmap/IndicatorTitle/index.js

Adds tooltip to chart actions
Please delete options that are not relevant.

[Feature] Add Tooltip To Chart Actions

---

src/components/HURUmap/Chart/index.js
src/components/HURUmap/Chart/index.stories.js

- Handle unrecognised filter value

[Bug] Error handling unrecognised filter value

---

src/components/HURUmap/Chart/index.js
src/components/HURUmap/KeyMetric/index.js
src/components/HURUmap/KeyMetric/useStyles.js
src/components/HURUmap/Source/index.js
src/components/HURUmap/Source/index.stories.js

Metric source

---

src/components/HURUmap/Chart/index.js
src/components/HURUmap/IndicatorTitle/Share.js
src/components/StoriesInsights/useStyles.js

- Update iframe wrapper styles

Fix Extra spaces on embed iframe

---

src/components/HURUmap/Chart/DonutChartScope.js

- Define data domain for legend scales
https://user-images.githubusercontent.com/7962097/161225875-dc2bc72d-4fb3-40a7-a984-500915b87ece.mov

Donut: Define explicit domain on scales

---

src/components/Sources/Dataset.js
src/components/Sources/index.js
src/components/Sources/useStyles.js
src/utils/fetchOpenAfricaDatasets.js

- Show unique file type tags for Document
- Update styles

[Chore] Unique Datasets file tags

---

src/components/DatasetsAndDocuments/index.js
src/components/DatasetsAndDocuments/useStyles.js
src/components/Sources/List.js
src/components/Sources/index.js
src/components/Sources/useStyles.js

- Use FE pagination for DatasetDocument Components
https://user-images.githubusercontent.com/7962097/162752707-e39b0f51-8569-408b-886b-8829416bcf7c.mov

[Bug] Fix heights for DatasetDocument Component

---

contrib/dokku/Dockerfile
package.json

Bump pesayetu site to version 0.2.1-alpha

Bump pesayetu site to version 0.2.1-alpha

---

contrib/dokku/Dockerfile
package.json
src/components/AboutTeam/index.js
src/components/Hero/index.js

Improve Responsive

---

contrib/dokku/Dockerfile
package.json
src/components/HURUmap/Chart/index.js
src/components/HURUmap/IndicatorTitle/index.js
src/components/HURUmap/KeyMetric/index.js
src/components/HURUmap/Panel/DesktopPanel/PanelButtons.js
src/components/HURUmap/Panel/DesktopPanel/index.js
src/components/HURUmap/Panel/ProfileItems.js
src/components/Page/Base.js
src/functions/menus/getNavigationMenu.js
src/pages/embed/[geoCode]/[chartId].js
yarn.lock

When embed page is open (not in an iframe), there is no way for someone to that there is actually more content on the site. This PR improves this situation by:
Standalone mode vs when embedded in an iframe

Improve embed page

---

contrib/dokku/Dockerfile
package.json
src/components/HURUmap/Panel/MobilePanel/index.js
src/components/HURUmap/Panel/Profile.js
src/components/HURUmap/PinAndCompare/index.js

Ensure the correct `geographyCode` props is passed to the PinAndCompare Component
The current location is not being Filtered since the `geographyCode` wasn't being passed in.

Ensure the correct geographyCode props is passed to the PinAndCompare Component

---

contrib/dokku/Dockerfile
package.json
src/components/HURUmap/Chart/index.js
src/components/SupportingPartners/index.js

This PR reduces minimum size required to render full chart from 768px to 600px. The goal being to improve embedded chart rendering.

Improve chart mobile sizing
